def gen = new File(basedir, 'target/classes/integration/test')
assert new File(gen, 'Test.class').exists()
assert new File(gen, 'Query.class').exists()
assert new File(gen, 'UnnamedQuery.class').exists()
assert new File(gen, 'TrackingInfoQuery.class').exists()
assert new File(gen, 'ItemsInDeliveryByPaymentQuery.class').exists()
assert new File(gen, 'Mutation.class').exists()
assert new File(gen, 'DeliveredMutation.class').exists()
assert new File(gen, 'types/Item.class').exists()
assert new File(gen, 'types/Location.class').exists()
assert new File(gen, 'types/LocationOrTrack.class').exists()
assert new File(gen, 'types/Mutation.class').exists()
assert new File(gen, 'types/PaymentType.class').exists()
assert new File(gen, 'types/Query.class').exists()
assert new File(gen, 'types/SoldItem.class').exists()
assert new File(gen, 'types/TimedFromTo.class').exists()
assert new File(gen, 'types/Track.class').exists()
assert new File(gen, 'types/TrackedFromTo.class').exists()
