def gen = new File(basedir, 'target/classes/integration/test')
assert new File(gen, 'Query.class').exists()
assert new File(gen, 'UnnamedQuery.class').exists()
assert new File(gen, 'GetTrackingInfoQuery.class').exists()
assert new File(gen, 'GetItemsInDeliveryByPaymentQuery.class').exists()
assert new File(gen, 'Mutation.class').exists()
assert new File(gen, 'SetDeliveredMutation.class').exists()
assert new File(gen, 'types/Item.class').exists()
assert new File(gen, 'types/Location.class').exists()
assert new File(gen, 'types/PaymentType.class').exists()
assert new File(gen, 'types/SoldItem.class').exists()
assert new File(gen, 'types/Track.class').exists()
assert new File(gen, 'types/Query.class').exists()
assert new File(gen, 'types/Mutation.class').exists()
